version: "3.3"

services:
  server:
    build: ./
    command: bash -c "npm i && npm run dev"
    volumes:
      - ./:/cloud-browser
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://mongodb:27017/cloud_browser
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
